language: python
matrix:
  include:
    - python: "pypy"
      env: TOX_ENV=pypy
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "2.7"
      env: TOX_ENV=cover
install:
  - if [ "x$TOX_ENV" = 'xcover' ]; then pip install coveralls --use-mirrors; fi
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - if [ "x$TOX_ENV" = 'xcover' ]; then coveralls --use-mirrors; fi
